name: EcomStadtverwaltung
main: de.wavecom_web.bukkit.ecomMySQL
version: 1.2
depend: [Vault, WorldGuard] 
commands:
   stadtkasse:
      description: Stadtkasse.
      usage: /<command>
   stadtwahl:
      description: Stadtwahl.
      usage: /<command>
   getlizenz:
      description: Getlizenz.
      usage: /<command>
   lizenzinfo:
      description: Lizenzinfo.
      usage: /<command>
   canceljob:
      description: Job beenden.
      usage: /<command>
   lizenzgetrights:
      description: Rechtevergabe fuer WorldGuard Lizenz vergebung.
      usage: /<command>
   editstadt:
      description: Stadt eines Users veraendern.
      usage: /<command>
   deljob:
      description: Lizenz zuruecksetzten.
      usage: /<command>
   muteall:
      description: Alle muten
      usage: /<command>
   unmuteall:
      description: Alle unmuten
      usage: /<command>
   startlogo:
      permission: wavecom.logo
      permissions: wavecom.logo
      description: Logo
      usage: /<command>

