name: EcomStadtverwaltung
main: de.wavecom_web.bukkit.ecomMySQL
version: 1.0
depend: [Vault] 
commands:
   stadtkasse:
      description: Stadtkasse.
      usage: /<command>
      permission: wavecom.stadt
      permission-message: You don't have <permission>
   stadtwahl:
      description: Stadtwahl.
      usage: /<command>
      permission: wavecom.stadtwahl
      permission-message: You don't have <permission>
