name: EcomStadtverwaltung
main: de.wavecom_web.bukkit.ecomMySQL
version: 1.0
depend: [Vault, WorldGuard] 
commands:
   stadtkasse:
      description: Stadtkasse.
      usage: /<command>
   stadtwahl:
      description: Stadtwahl.
      usage: /<command>
   getlizenz:
      description: Getlizenz.
      usage: /<command>
   canceljob:
      description: Job beenden.
      usage: /<command>
   lizenzgetrights:
      description: Rechtevergabe fuer WorldGuard Lizenz vergebung.
      usage: /<command>
